.travis.yml

Requires that the Travis CI service has the correct permissions to the
repository, and that an environment variable called GH_TOKEN is present.

Add Travis CI file

---

README.md
eventstream.go
eventstream_test.go
example/main.go
repository.go
repository_test.go

Removes the go-observer pkg dependency with a call to registered function when events are saved to repository.
Where is nothing wrong with the go-observer pkg but it seams that it should be used outside this package if needed. This solution opens open a more generic way of handling real time events.

Event stream func

---

eventstream.go
eventstream_test.go
repository.go
repository_test.go

take cares of possible concurrency problems between multiple event subscribers

add lock to event stream to run subscribing func in sync with the events

---

README.md
eventsourcing.go
eventstream.go
eventstream_test.go
repository.go
repository_test.go

Makes it possible to subscribe to events from a specific aggregate instance. Based on aggregate type and identity.

Subscribe specific aggregate

---

README.md
eventsourcing.go
eventstream.go
eventstream_test.go
repository.go
serializer.go
serializer_test.go
snapshotstore/memory.go

Exported the Aggregate interface and reduced the methods from ->
```go
type aggregate interface {
ID() string
path() string	
BuildFromHistory(a aggregate, events []Event)	
Transition(event Event)
Events() []Event	
UnsavedEvents() bool	
updateVersion()	
Version() Version	
SetID(id string) error	
}
```
to
```go
type Aggregate interface {
Root() *AggregateRoot
Transition(event Event)
}
```
where the Root() method return a pointer to the internal AggregateRoot struct.

Aggregate interface

---

README.md
eventsourcing.go
eventsourcing_test.go
example/main.go
go.mod
go.sum
idgenerator.go

Aggregate ID's are by default generated via the crypt/rand pkg instead of a external uuid pkg.
This could be changed via the global SetIDFunc.

Removed all external dependencies from the main eventsourcing pkg

---

eventsourcing.go
eventstore/bbolt/bbolt.go
eventstore/bbolt/go.mod
eventstore/memory/memory.go
eventstore/sql/go.mod
eventstore/sql/sql.go
eventstore/suite/suite.go
repository.go
repository_test.go

Change that an eventstore return an ErrNoEvents when there is no events when trying to get events for an aggregate.

return ErrNoEvents when no events for an aggregate

---

README.md
eventstore/bbolt/bbolt.go
eventstore/bbolt/go.mod
eventstore/memory/memory.go
eventstore/sql/go.mod
eventstore/sql/sql.go
eventstore/suite/suite.go
repository.go
serializer_test.go

Makes it possible to iterate the event stream and for example build read models asynchronously.

Global event get

---

README.md
serializer.go
snapshot.go
snapshot_test.go

A way to handle none exported properties on a aggregate when taking a snapshot.

Snapshot none exported properties

---

README.md
serializer.go
serializer_test.go

Makes the event registration simpler.
s.RegisterTypes(&SomeAggregate{}, func() interface{} { return &SomeData{} }, func() interface{} { return &SomeData2{} })
s.Register(&SomeAggregate{}, s.**Events**(&SomeData{}, &SomeData2{}))
The "old" method RegisterTypes will still be present to keep backwards compatibility.

Serializer Events() method

---

README.md
event.go
eventstore/bbolt/bbolt.go
eventstore/bbolt/iterator.go
eventstore/esdb/esdb.go
eventstore/esdb/iterator.go
eventstore/memory/memory.go
eventstore/sql/iterator.go
eventstore/sql/sql.go
eventstore/suite/suite.go
repository.go
repository_test.go
snapshot.go
snapshot_test.go
snapshotstore/memory/memory.go
snapshotstore/sql/sql.go
snapshotstore/suite/suite.go

Make evenstore´s return an event iterator instead of a slice of events. To make the event fetching more stream based and reduce memory pressure.

Event iterator

---

.gitignore
README.md
event.go
event_test.go
eventstream.go
eventstream_test.go
repository.go
repository_test.go

When different parts of an application wants to subscribe to events from the repository but don't want to reference the specific aggregate or event types. ~~Instead of returning the `eventsourcing.Event` a new type is introduced `eventsourcing.EventUntyped`. This new type is the same as `eventsourcing.Event` but the `Data` property is a `map[string]interface{}` instead of an `interface{}`. This makes it possible to handle the events in an untyped form without the typed application events.~~ New methods is introduced making it possible to subscribe by aggregate and event names. The `eventsourcing.Event` expose a `DataAs(i interface{}) error` where the `Data` property on the event can be transformed to a new type. 
The idea came from the book Strategic Monoliths and Microservices and the …

Eventstream retake

---

README.md
serializer.go
serializer_test.go

The current way to register aggregate event to the serialiser is via methods on the serialiser entity.
```go
s := eventsourcing.NewSerializer(json.Marshal, json.Unmarshal)
err := s.Register(&SomeAggregate{}, ser.Event(&SomeData{}))
```
By adding events to the serialiser appart from the aggregate code makes it easy to miss register newly added events. This will have the effect that the event will not be handled in aggregate `Transition(event eventsourcing.Event)` method when building the aggregate from events that are fetched from the eventstore. By adding a new optional method `RegisterEvents` on the aggregate this makes it's harder to miss.
```go
// new method on the aggregate that will be called when using the steriliser method RegisterAggregate
func (s *SomeAggregate) RegisterEvents(f …
```

RegisterEvents method on the aggregate

---

eventstore/esdb/esdb.go
eventstore/sql/sql.go
repository.go

In the current implementation there is a risk of resource leak.

Better handling contexts

---

README.md
core/eventstore.go
core/nopiterator.go
core/testsuite/suite.go
eventstore/bbolt/go.mod
eventstore/bbolt/iterator.go
eventstore/esdb/esdb.go
eventstore/esdb/go.mod
eventstore/esdb/iterator.go
eventstore/memory/memory.go
eventstore/sql/go.mod
eventstore/sql/iterator.go
go.mod
repository.go

Change the iterator interface to make the communication between the event store's and the main package smoother.
Before:
```go
type Iterator interface {
Next() (Event, error)
Close()
}
```
After:
```go
type Iterator interface {
Next() bool
Value() (Event, error)
Close()
}
```
The error handling is a lot simpler as the end of an event stream does not have to be returned as en error anymore.

Iterator interface re-design

---

aggregateroot.go
eventrepository.go
eventstream.go
example/go.mod
example/go.sum
example/main.go
go.mod
internal/register.go
snapshotrepository.go

Start use an internal package to hide structs, methods and functions that does not have to be public to the outside.

Internal package

---

aggregateroot_test.go
eventstore/bbolt/bbolt.go
eventstore/bbolt/go.mod
eventstore/bbolt/go.sum
eventstore/bbolt/iterator.go

Make use of the underlaying cursor instead of reading the events into memory before iterating.

bbolt eventstore refactor

---

eventstore/sql/README.md
eventstore/sql/sql.go
eventstore/sql/sql_test.go

If sql event store is constructed with the `OpenWithSingelWriter ` constructor aggregate events are stored singel threaded.

OpenWithSingelWriter constructor in sql event store

---

aggregateroot.go
eventrepository.go
eventstream.go
snapshotrepository.go

Hide the method on the aggregate interface as for internal use only.

chore(aggregate)!: aggregate interface method Root -> root

---

.github/workflows/go.yml

Potential fix for [https://github.com/hallgren/eventsourcing/security/code-scanning/5](https://github.com/hallgren/eventsourcing/security/code-scanning/5)
To fix the issue, we will add a `permissions` block at the root level of the workflow. This block will apply to all jobs in the workflow unless overridden by job-specific `permissions` blocks. Since the workflow primarily involves building and testing a Go project, it only requires read access to the repository contents. Therefore, we will set `contents: read` as the minimal required permission.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 5: Workflow does not contain permissions

---

iterator.go
projections.go
projections_test.go

Return `Event` containing the underlying `event` from iterator so that error message values can be populated.
Resolves https://github.com/hallgren/eventsourcing/issues/160
I'm not confident that this is the best way of resolving the issue, but worked for me locally when trying to debug my project.

Fix empty ErrEventNotRegistered error message

---

aggregate/aggregate.go
aggregate/root.go
aggregate/snapshot.go

* Removed the aggregate name extension as the variables are already in the aggregate package.
* Removed the unused methods `update` and `path` from the aggregate root.

chore: restructure internals and remove dead code
