hallgren/eventsourcing

eventsourcing.go
eventstore/eventstore.go
eventstore/sql/migrate.go
eventstore/sql/sql.go
example/frequent_flier_account.go
example/status_string.go
repository.go
serializer/json/json.go
serializer/unsafe/unsafe.go
snapshotstore/memory.go

support go linter

---

README.md

Eventstream

---

README.md
eventstream.go
eventstream_test.go
example/main.go
repository.go
repository_test.go

make it possible to subscribe to specific events. Need some time and thought to make sure the api and the internal thinks is ok.

WIP: Eventstream subscribe to specific events

---

README.md
eventsourcing.go
eventsourcing_test.go
serializer/json/json.go
serializer/serializer_test.go
serializer/unsafe/unsafe.go

Its pretty neat with a timestamp on the events...

Event timestamp

---

README.md
eventstore/bbolt/bbolt.go
eventstore/eventstore_test.go
eventstore/memory/memory.go
eventstore/sql/sql.go

Currently not used, re-add if needed.

remove the GlobalGet function from the eventstores

---

eventstore/sql/migrate.go
eventstore/sql/sql.go

remove the unused meta data column from the sql schema

WIP: Sql remove metadata column

---

eventstore/memory/memory.go
eventstore/suite/suite.go

Make the memory backed event store thread safe in the Save method.

Eventstore concurrent test

---

Makefile
eventsourcing.go
eventsourcing_test.go
go.mod
go.sum

Switch module for generating UUID on aggregates.

Use google/uuid module for UUID

---

README.md
repository.go
repository_test.go
serializer.go
serializer_test.go
snapshotstore/memory.go
snapshotstore/memory_test.go

Move out the serializer to the main pkg.

move serializer to main eventsourcing pkg

---

eventstore/sql/migrate.go
eventstore/sql/sql_test.go
snapshotstore/sql/go.mod
snapshotstore/sql/go.sum
snapshotstore/sql/migrate.go

Sql migrate tx

---

README.md
eventsourcing.go
eventstore/bbolt/bbolt.go
eventstore/bbolt/go.mod
eventstore/eventstore.go
eventstore/memory/memory.go
eventstore/sql/go.mod
eventstore/sql/sql.go
eventstore/suite/suite.go

Make the Event more inline with the Aggregate.

event id is now named AggregateID instead of AggregateRootID

---

README.md
eventsourcing.go
eventsourcing_test.go
eventstore/bbolt/bbolt.go
eventstore/bbolt/bbolt_test.go
eventstore/bbolt/go.mod
eventstore/memory/memory.go
eventstore/sql/go.mod
eventstore/sql/sql.go
eventstore/suite/suite.go
repository.go
repository_test.go

Expose the event version based on all events stored in an event store.
Before merge finish the eventstore.org implementation to make sure this concept fit that storage.

WIP: GlobalVersion on events

---

README.md
eventsourcing.go
eventstore/bbolt/bbolt.go
eventstore/bbolt/go.mod
eventstore/memory/memory.go
eventstore/sql/go.mod
eventstore/sql/sql.go
eventstore/suite/suite.go
repository.go
repository_test.go

Sets the GlobalVersion on the events after saved instead of returning the last GlobalVersion.

Global version retake

---

eventsourcing.go
eventsourcing_test.go
repository.go

Prevent external mutation of aggregate events.

Prevent external event mutations

---

README.md
aggregateroot.go
aggregateroot_test.go
event.go
eventstore/bbolt/bbolt.go
eventstore/bbolt/go.mod
eventstore/sql/go.mod
eventstore/sql/sql.go
eventstore/suite/suite.go
example/go.mod
snapshotstore/sql/go.mod

Rename the property MetaData to Metadata.

rename MetaData -> Metadata

---

eventstore/sql/iterator.go
eventstore/sql/sql.go

Make sure Sql rows.Err() not contain error

---

aggregateroot.go
eventrepository.go
eventstream.go
register.go
snapshotrepository.go

The internal package was a bad idea for the problem I try to solve with it.

Revert internal package 

---

example/README.md
example/go.mod
example/go.sum

Examples readme

---

README.md
encoderjson.go
eventrepository.go
register.go
snapshotrepository.go

The Encoder interaface can better combine the previous Serializer/Deserializer functions.

Encoder interface

---

.github/workflows/go.yml
Makefile

This adds a minimal example of a workflow that checks push on master branch and pull requests (targeting master).

Add workflow for PR checks

---

.github/workflows/go.yml

update GitHub action checkout v4 and setup-go v5

github checkout action v3 -> v4

---

.github/workflows/go.yml
README.md
go.mod
projections.go
projections_test.go

Trigger a running projection instead of waiting for the timer to fire.

projection trigger

---

example/tictactoe/tictactoe.go
example/tictactoe/tictactoe_test.go

A base example that can be used to try ideas on like realtime events and also show how to use different features.

docs(example): tic-tac-toe 
